// Auth action types
export const AUTH_START = 'AUTH_START';
export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';
export const AUTH_ADMIN_VERIFY_SUCCESS = 'AUTH_ADMIN_VERIFY_SUCCESS';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_HASH = 'SET_HASH';



// Backend
export const RESET_DASHBOARD = 'RESET_DASHBOARD';
export const DASHBOARD_START = 'DASHBOARD_START';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAIL = 'DASHBOARD_FAIL';

export const RESET_ATTENDANCE_REPORT = 'RESET_ATTENDANCE_REPORT';
export const ATTENDANCE_REPORT_START = 'ATTENDANCE_REPORT_START';
export const ATTENDANCE_REPORT_SUCCESS = 'ATTENDANCE_REPORT_SUCCESS';
export const ATTENDANCE_REPORT_FAIL = 'ATTENDANCE_REPORT_FAIL';

export const RESET_CALENDAR = 'RESET_CALENDAR';
export const CALENDAR_START = 'CALENDAR_START';
export const CALENDAR_SUCCESS = 'CALENDAR_SUCCESS';
export const CALENDAR_FAIL = 'CALENDAR_FAIL';

export const RESET_TASKS = 'RESET_TASKS';
export const TASKS_START = 'TASKS_START';
export const TASKS_SUCCESS = 'TASKS_SUCCESS';
export const TASKS_FAIL = 'TASKS_FAIL';

export const RESET_MESSAGES = 'RESET_MESSAGES';
export const MESSAGES_START = 'MESSAGES_START';
export const MESSAGES_SUCCESS = 'MESSAGES_SUCCESS';
export const MESSAGES_FAIL = 'MESSAGES_FAIL';

export const RESET_REQUESTS = 'RESET_REQUESTS';
export const REQUESTS_START = 'REQUESTS_START';
export const REQUESTS_SUCCESS = 'REQUESTS_SUCCESS';
export const REQUESTS_FAIL = 'REQUESTS_FAIL';

export const RESET_CHAT = 'RESET_CHAT';
export const CHAT_START = 'CHAT_START';
export const CHAT_SUCCESS = 'CHAT_SUCCESS';
export const CHAT_MESSAGE_SUCCESS = 'CHAT_MESSAGE_SUCCESS';
export const CHAT_FAIL = 'CHAT_FAIL';